from pathlib import Path
import unittest


PROJECT_ROOT = Path(__file__).resolve().parents[1]


class AppSecSttTermsTests(unittest.TestCase):
    def test_browser_monitor_uses_deepgram_keyterms(self) -> None:
        app_js = (PROJECT_ROOT / "web/static/js/app.js").read_text(encoding="utf-8")

        self.assertIn("const DEEPGRAM_KEYTERMS = Object.freeze", app_js)
        self.assertIn("'SBOM'", app_js)
        self.assertIn("'Software Bill of Materials'", app_js)
        self.assertIn("'mTLS'", app_js)
        self.assertIn("'Base64'", app_js)
        self.assertIn("'B64'", app_js)
        self.assertIn("'X.509'", app_js)
        self.assertIn("'certificate'", app_js)
        self.assertIn("'cert'", app_js)
        self.assertIn("'tcpdump'", app_js)
        self.assertIn("'DevSecOps'", app_js)
        self.assertIn("'K2'", app_js)
        self.assertIn("'PC/SC'", app_js)
        self.assertIn("'PC/SC reader'", app_js)
        self.assertIn("'traceroute'", app_js)
        self.assertIn("'GitLab'", app_js)
        self.assertIn("'Harbor'", app_js)
        self.assertIn("'Nexus'", app_js)
        self.assertIn("'Jira'", app_js)
        self.assertIn("'Google Cybersecurity'", app_js)
        self.assertIn("'Keycloak'", app_js)
        self.assertIn("'SonarQube'", app_js)
        self.assertIn("'HSM'", app_js)
        self.assertIn("'Rutoken'", app_js)
        self.assertIn("'Astra'", app_js)
        self.assertIn("'USB socket'", app_js)
        self.assertIn("'Firecracker'", app_js)
        self.assertIn("'node group'", app_js)
        self.assertIn("'OIDC'", app_js)
        self.assertIn("'YubiKey'", app_js)
        self.assertIn("'CryptoPro'", app_js)
        self.assertIn("'CryptoPro plugin'", app_js)
        self.assertIn("'Treasure API'", app_js)
        self.assertIn("'Kafka'", app_js)
        self.assertIn("'VRF'", app_js)
        self.assertIn("'Burp Suite'", app_js)
        self.assertIn("'Burp Suite Professional'", app_js)
        self.assertIn("'OWASP ZAP'", app_js)
        self.assertIn("'OpenVAS'", app_js)
        self.assertIn("'Nuclei'", app_js)
        self.assertIn("'Semgrep'", app_js)
        self.assertIn("'DefectDojo'", app_js)
        self.assertIn("'Trivy'", app_js)
        self.assertIn("'Wazuh'", app_js)
        self.assertIn("'SOC analyst'", app_js)
        self.assertIn("'runbook'", app_js)
        self.assertIn("'bastion'", app_js)
        self.assertIn("'IAM policies'", app_js)
        self.assertIn("'cluster-admin'", app_js)
        self.assertIn("'node exporter'", app_js)
        self.assertIn("'HashiCorp Vault'", app_js)
        self.assertIn("'SDLC'", app_js)
        self.assertIn("'TDX'", app_js)
        self.assertIn("'VM'", app_js)
        self.assertIn("'polling'", app_js)
        self.assertIn("'downtime'", app_js)
        self.assertIn("'AWS'", app_js)
        self.assertIn("'WAF'", app_js)
        self.assertIn("'TypeScript'", app_js)
        self.assertIn("'SSH ключи'", app_js)
        self.assertIn("const MAX_KEYTERM_QUERY_CHARS = 2500", app_js)
        self.assertIn("function deepgramKeytermsSupported(lang)", app_js)
        self.assertIn("function appendDeepgramKeyterms(params, lang)", app_js)
        self.assertIn("params.append('keyterm', term)", app_js)

    def test_browser_monitor_normalizes_appsec_terms_before_render(self) -> None:
        app_js = (PROJECT_ROOT / "web/static/js/app.js").read_text(encoding="utf-8")

        self.assertIn("function normalizeAppSecTerms(text)", app_js)
        self.assertIn("[/\\bтандж(?:и|ем|ему|а|ей)?\\b/giu, 'Tangem']", app_js)
        self.assertIn("[/\\bSecurity\\s+assistant\\s+of\\s+crypto\\s+wallet\\s+back\\s+end\\s+IP\\s+before\\s+a\\s+major\\s+release\\b/gi, 'Security assessment of crypto wallet backend and API before a major release']", app_js)
        self.assertIn("[/\\bHow\\s+do\\s+you\\s+decide\\s+whether\\s+a\\s+bad\\s+boundary\\s+report\\s+is\\s+critical\\s+heights,\\s+medium\\s+low\\s+severity\\b/gi, 'How do you decide whether a bug bounty report is critical, high, medium, or low severity']", app_js)
        self.assertIn("[/\\bHow\\s+wolf\\s+do\\s+you\\s+validate\\s+where\\s+embark\\s+bounty\\s+reports\\b/gi, 'How would you validate whether bug bounty reports']", app_js)
        self.assertIn("[/\\bHow\\s+old\\s+do\\s+you\\s+tune\\s+cloud\\s+photo\\s+of\\s+of\\s+IP\\s+shield\\s+Aurelius\\b/gi, 'How would you tune Cloudflare or IP shield rules']", app_js)
        self.assertIn("[/\\bIn\\s+this\\s+to\\s+gauge\\s+whether\\s+I\\s+love\\s+rule,\\s+he\\s+is\\s+blocking\\s+leg\\s+team\\s+users\\s+or\\s+only\\s+malicious\\s+traffic\\b/gi, 'How would you gauge whether a WAF rule is blocking legitimate users or only malicious traffic']", app_js)
        self.assertIn("[/\\bHow\\s+old\\s+do\\s+you\\s+build\\s+security\\s+code\\s+and\\s+training\\s+for\\s+back\\s+end\\s+developers\\s+who\\s+work\\s+with\\s+Abyss\\b/gi, 'How would you build secure coding training for backend developers who work with APIs']", app_js)
        self.assertIn("[/\\bTo\\s+integrate\\s+SAS\\s+into\\s+a\\s+CS\\s+and\\s+you\\s+without\\s+blocking\\s+every\\s+match\\.\\s*Request\\b/gi, 'How would you integrate SAST into CI/CD without blocking every merge request']", app_js)
        self.assertIn("[/\\bHow\\s+old\\s+do\\s+you\\s+tune\\s+in\\s+above\\s+her\\s+rule\\s+that\\s+Melox\\s+and\\s+mobile\\s+IP\\s+traffic\\b/gi, 'How would you tune a WAF rule that blocks legitimate mobile API traffic']", app_js)
        self.assertIn("[/\\bHow\\s+do\\s+you\\s+taste\\s+my\\s+mobile\\s+IP\\s+traffic\\s+for\\s+after\\s+two\\s+authorization\\s+and\\s+for\\s+And\\s+follow\\s+flows\\b/gi, 'How do you test deep links and universal links for account takeover risks']", app_js)
        self.assertIn(")даст\\b/giu, '$1DAST']", app_js)
        self.assertIn(")саст\\b/giu, '$1SAST']", app_js)
        self.assertIn(")ска\\b/giu, '$1SCA']", app_js)
        self.assertNotIn("что\\s+это|объясни", app_js)
        self.assertIn("[/\\bWhy\\s+wall\\s+three\\s+tests\\s+were\\s+there\\s+an\\s+API\\s+endpoint\\?\\s*Clicks\\s+sensitive\\s+wallet\\s+metadata\\s+throughout\\s+a\\s+xsife\\.expo\\s+exp\\s+exp\\s+exp\\b/gi, 'What would you test when an API endpoint leaks sensitive wallet metadata through XSS exposure']", app_js)
        self.assertIn("[/\\bI\\s+will\\s+suit\\s+this\\s+weather\\s+cause\\s+an\\s+exploitable\\s+riser\\s+that\\s+just\\s+misconfigurate\\b/gi, 'How would you decide whether this is an exploitable risk or just a misconfiguration']", app_js)
        self.assertIn("[/\\bOh,\\s*hold\\s+to\\s+your\\s+comfy\\s+clothes\\.\\s*Api\\s+shield\\.\\s*She's\\s+having\\s+validation\\.\\s*And\\s+what\\s+traffic\\s+vault\\s+you\\s+put\\s+into\\s+lock\\s+mode\\s+before\\s+unlocking\\b/gi, 'How would you configure Cloudflare API Shield schema validation, and what traffic would you put into log mode before blocking']", app_js)
        self.assertIn("[/\\bbusiness\\s+log\\s+for\\s+vulnerabilities\\s+that\\s+Aftermath\\s+scanner\\s+usually\\s+miss\\b/gi, 'business logic vulnerabilities that automated scanners usually miss']", app_js)
        self.assertIn("[/\\bapplication\\s+security\\s+check\\s+and\\s+c\\s*s\\s*c\\s*d\\s+pipeline\\b/gi, 'application security checks into a CI/CD pipeline']", app_js)
        self.assertIn("[/\\bSAS\\s+into\\s+a\\s+CS\\s+and\\s+you\\b/gi, 'SAST into CI/CD']", app_js)
        self.assertIn("[/\\bblocking\\s+every\\s+match\\.\\s*Request\\b/gi, 'blocking every merge request']", app_js)
        self.assertIn("[/\\babove\\s+her\\s+rule\\b/gi, 'WAF rule']", app_js)
        self.assertIn("[/\\bMelox\\s+and\\s+mobile\\s+IP\\s+traffic\\b/gi, 'blocks legitimate mobile API traffic']", app_js)
        self.assertIn("[/\\btaste\\s+my\\s+mobile\\s+IP\\s+traffic\\b/gi, 'test deep links and universal links']", app_js)
        self.assertIn("[/\\bafter\\s+two\\s+authorization\\s+and\\s+for\\s+And\\s+follow\\s+flows\\b/gi, 'account takeover risks']", app_js)
        self.assertIn("[/\\bdefsy\\s+cops\\b/gi, 'DevSecOps']", app_js)
        self.assertIn("[/\\btrife\\s+roads\\b/gi, 'traceroute']", app_js)
        self.assertIn("[/\\bBISC\\s*-?\\s*64\\b/gi, 'Base64']", app_js)
        self.assertIn("[/\\bSertu\\b/gi, 'cert']", app_js)
        self.assertIn("[/\\bd\\s*DevOps\\b/gi, 'DevOps']", app_js)
        self.assertIn("[/\\bdelops\\b/gi, 'DevOps']", app_js)
        self.assertIn("[/\\bPDX\\b/gi, 'TDX']", app_js)
        self.assertIn("[/\\bQD\\s*2\\b/gi, 'K2']", app_js)
        self.assertIn("])ик\\s*-?\\s*2(?=$|[^A-Za-zА-Яа-яЁё0-9_])/giu, '$1K2']", app_js)
        self.assertIn("])ка\\s*-?\\s*2(?=$|[^A-Za-zА-Яа-яЁё0-9_])/giu, '$1K2']", app_js)
        self.assertIn("[/канал\\s+ик\\s*-?\\s*2/giu, 'канал K2']", app_js)
        self.assertIn("[/\\bhsam\\b/gi, 'HSM']", app_js)
        self.assertIn("[/\\bPCC\\b/g, 'PC/SC']", app_js)
        self.assertIn("[/\\bdimetime\\b/gi, 'downtime']", app_js)
        self.assertIn("[/\\bGETLab\\b/gi, 'GitLab']", app_js)
        self.assertIn("[/\\bHarva\\b/gi, 'Harbor']", app_js)
        self.assertIn("[/\\bNetsus\\b/gi, 'Nexus']", app_js)
        self.assertIn("[/\\bVolta\\b/gi, 'Vault']", app_js)
        self.assertIn("[/\\bTwe\\s+City\\b/gi, 'TeamCity']", app_js)
        self.assertIn("[/\\bnot\\s+group\\b/gi, 'node group']", app_js)
        self.assertIn("[/\\bfirecraker\\b/gi, 'Firecracker']", app_js)
        self.assertIn("[/\\bkicklog\\b/gi, 'Keycloak']", app_js)
        self.assertIn("[/\\bjiva\\b/gi, 'Jira']", app_js)
        self.assertIn("[/\\bGoogle\\s+Server\\s+Secutive\\b/gi, 'Google Cybersecurity']", app_js)
        self.assertIn("[/\\bSelect\\s+tell\\b/gi, 'Selectel']", app_js)
        self.assertIn("[/\\bSliktelry\\b/gi, 'Selectel']", app_js)
        self.assertIn("[/\\bkeyclock\\b/gi, 'Keycloak']", app_js)
        self.assertIn("[/\\bOEDC\\b/gi, 'OIDC']", app_js)
        self.assertIn("[/\\bUBK\\b/gi, 'YubiKey']", app_js)
        self.assertIn("[/\\bClibreprood\\s+tools\\b/gi, 'CryptoPro tools']", app_js)
        self.assertIn("[/\\bCryptuPro\\b/gi, 'CryptoPro']", app_js)
        self.assertIn("[/\\bCryptoProp\\b/gi, 'CryptoPro']", app_js)
        self.assertIn("[/\\bC(?:op|rop)ois\\b/gi, 'CryptoPro CSP']", app_js)
        self.assertIn("[/\\bTreshare\\s+IP\\b/gi, 'Treasure API']", app_js)
        self.assertIn("[/\\bCafку\\b/giu, 'Kafka']", app_js)
        self.assertIn("[/\\bSSSH\\b/gi, 'SSH']", app_js)
        self.assertIn("[/\\bSOKET\\b/g, 'socket']", app_js)
        self.assertIn("[/\\bRegistery\\b/gi, 'registry']", app_js)
        self.assertIn("[/\\bboost\\b/gi, 'Burp Suite']", app_js)
        self.assertIn("[/\\bburg\\s+suite(?:\\s+professional)?\\b/gi, 'Burp Suite Professional']", app_js)
        self.assertIn("[/\\bо\\s+вас\\s+к\\s+западу\\b/giu, 'OWASP ZAP']", app_js)
        self.assertIn("[/\\bNucai\\b/gi, 'Nuclei']", app_js)
        self.assertIn("[/\\bSimGreb\\b/gi, 'Semgrep']", app_js)
        self.assertIn("[/\\bsing\\s+gr[ae]p\\b/gi, 'Semgrep']", app_js)
        self.assertIn("[/\\beTrivy\\b/gi, 'Trivy']", app_js)
        self.assertIn("[/\\bdefect\\s+dother\\b/gi, 'DefectDojo']", app_js)
        self.assertIn("[/\\bвозух\\b/giu, 'Wazuh']", app_js)
        self.assertIn("[/сока\\s+налиток/giu, 'SOC analyst']", app_js)
        self.assertIn("[/рандбук(?:а|и|ов|ом)?/giu, 'runbook']", app_js)
        self.assertIn("[/\\beam\\s+politik\\b/gi, 'IAM policies']", app_js)
        self.assertIn("[/\\bcluster\\s+admin\\b/gi, 'cluster-admin']", app_js)
        self.assertIn("[/\\bforwall\\b/gi, 'firewall']", app_js)
        self.assertIn("pending.transcript = normalizeAppSecTerms(m[2]);", app_js)
        self.assertIn("const text = normalizeAppSecTerms(tabFinalText);", app_js)

    def test_rust_stt_normalizes_appsec_terms_before_returning_result(self) -> None:
        stt_rs = (PROJECT_ROOT / "native/audio_engine/src/stt/mod.rs").read_text(
            encoding="utf-8"
        )

        self.assertIn("const DEEPGRAM_KEYTERMS: &[&str]", stt_rs)
        self.assertIn('"SBOM"', stt_rs)
        self.assertIn('"Software Bill of Materials"', stt_rs)
        self.assertIn('"mTLS"', stt_rs)
        self.assertIn('"Base64"', stt_rs)
        self.assertIn('"B64"', stt_rs)
        self.assertIn('"X.509"', stt_rs)
        self.assertIn('"certificate"', stt_rs)
        self.assertIn('"cert"', stt_rs)
        self.assertIn('"DevSecOps"', stt_rs)
        self.assertIn('"K2"', stt_rs)
        self.assertIn('"PC/SC"', stt_rs)
        self.assertIn('"PC/SC reader"', stt_rs)
        self.assertIn('"traceroute"', stt_rs)
        self.assertIn('"GitLab"', stt_rs)
        self.assertIn('"Harbor"', stt_rs)
        self.assertIn('"Nexus"', stt_rs)
        self.assertIn('"Jira"', stt_rs)
        self.assertIn('"Google Cybersecurity"', stt_rs)
        self.assertIn('"Keycloak"', stt_rs)
        self.assertIn('"SonarQube"', stt_rs)
        self.assertIn('"HSM"', stt_rs)
        self.assertIn('"Rutoken"', stt_rs)
        self.assertIn('"Astra"', stt_rs)
        self.assertIn('"USB socket"', stt_rs)
        self.assertIn('"Firecracker"', stt_rs)
        self.assertIn('"node group"', stt_rs)
        self.assertIn('"OIDC"', stt_rs)
        self.assertIn('"YubiKey"', stt_rs)
        self.assertIn('"CryptoPro"', stt_rs)
        self.assertIn('"CryptoPro plugin"', stt_rs)
        self.assertIn('"Treasure API"', stt_rs)
        self.assertIn('"Kafka"', stt_rs)
        self.assertIn('"VRF"', stt_rs)
        self.assertIn('"Burp Suite"', stt_rs)
        self.assertIn('"Burp Suite Professional"', stt_rs)
        self.assertIn('"OWASP ZAP"', stt_rs)
        self.assertIn('"OpenVAS"', stt_rs)
        self.assertIn('"Nuclei"', stt_rs)
        self.assertIn('"Semgrep"', stt_rs)
        self.assertIn('"DefectDojo"', stt_rs)
        self.assertIn('"Trivy"', stt_rs)
        self.assertIn('"Wazuh"', stt_rs)
        self.assertIn('"SOC analyst"', stt_rs)
        self.assertIn('"runbook"', stt_rs)
        self.assertIn('"bastion"', stt_rs)
        self.assertIn('"IAM policies"', stt_rs)
        self.assertIn('"cluster-admin"', stt_rs)
        self.assertIn('"node exporter"', stt_rs)
        self.assertIn('"HashiCorp Vault"', stt_rs)
        self.assertIn('"SDLC"', stt_rs)
        self.assertIn('"TDX"', stt_rs)
        self.assertIn('"VM"', stt_rs)
        self.assertIn('"polling"', stt_rs)
        self.assertIn('"downtime"', stt_rs)
        self.assertIn('("АВСе", "AWS")', stt_rs)
        self.assertIn('"Security assistant of crypto wallet back end IP before a major release"', stt_rs)
        self.assertIn('"Security assessment of crypto wallet backend and API before a major release"', stt_rs)
        self.assertIn('"How do you decide whether a bad boundary report is critical heights, medium low severity"', stt_rs)
        self.assertIn('"How do you decide whether a bug bounty report is critical, high, medium, or low severity"', stt_rs)
        self.assertIn('"How wolf do you validate where embark bounty reports"', stt_rs)
        self.assertIn('"How would you validate whether bug bounty reports"', stt_rs)
        self.assertIn('"How old do you tune cloud photo of of IP shield Aurelius"', stt_rs)
        self.assertIn('"How would you tune Cloudflare or IP shield rules"', stt_rs)
        self.assertIn('"In this to gauge whether I love rule, he is blocking leg team users or only malicious traffic"', stt_rs)
        self.assertIn('"How would you gauge whether a WAF rule is blocking legitimate users or only malicious traffic"', stt_rs)
        self.assertIn('"How old do you build security code and training for back end developers who work with Abyss"', stt_rs)
        self.assertIn('"How would you build secure coding training for backend developers who work with APIs"', stt_rs)
        self.assertIn('"To integrate SAS into a CS and you without blocking every match. Request"', stt_rs)
        self.assertIn('"How would you integrate SAST into CI/CD without blocking every merge request"', stt_rs)
        self.assertIn('"How old do you tune in above her rule that Melox and mobile IP traffic"', stt_rs)
        self.assertIn('"How would you tune a WAF rule that blocks legitimate mobile API traffic"', stt_rs)
        self.assertIn('"How do you taste my mobile IP traffic for after two authorization and for And follow flows"', stt_rs)
        self.assertIn('"How do you test deep links and universal links for account takeover risks"', stt_rs)
        self.assertIn('("танджи", "Tangem")', stt_rs)
        self.assertIn('("Что такое даст", "Что такое DAST")', stt_rs)
        self.assertIn('("Объясни саст", "Объясни SAST")', stt_rs)
        self.assertIn('("Расскажи про ска", "Расскажи про SCA")', stt_rs)
        self.assertNotIn('("Что это даст", "Что это DAST")', stt_rs)
        self.assertIn('"Why wall three tests were there an API endpoint? Clicks sensitive wallet metadata throughout a xsife.expo exp exp exp"', stt_rs)
        self.assertIn('"What would you test when an API endpoint leaks sensitive wallet metadata through XSS exposure"', stt_rs)
        self.assertIn('"I will suit this weather cause an exploitable riser that just misconfigurate"', stt_rs)
        self.assertIn('"How would you decide whether this is an exploitable risk or just a misconfiguration"', stt_rs)
        self.assertIn('"Oh, hold to your comfy clothes. Api shield. She\'s having validation. And what traffic vault you put into lock mode before unlocking"', stt_rs)
        self.assertIn('"How would you configure Cloudflare API Shield schema validation, and what traffic would you put into log mode before blocking"', stt_rs)
        self.assertIn('"business log for vulnerabilities that Aftermath scanner usually miss"', stt_rs)
        self.assertIn('"business logic vulnerabilities that automated scanners usually miss"', stt_rs)
        self.assertIn('"application security check and c s c d pipeline"', stt_rs)
        self.assertIn('"application security checks into a CI/CD pipeline"', stt_rs)
        self.assertIn('("SAS into a CS and you", "SAST into CI/CD")', stt_rs)
        self.assertIn('("blocking every match. Request", "blocking every merge request")', stt_rs)
        self.assertIn('("above her rule", "WAF rule")', stt_rs)
        self.assertIn('"Melox and mobile IP traffic"', stt_rs)
        self.assertIn('"blocks legitimate mobile API traffic"', stt_rs)
        self.assertIn('"taste my mobile IP traffic"', stt_rs)
        self.assertIn('"test deep links and universal links"', stt_rs)
        self.assertIn('"after two authorization and for And follow flows"', stt_rs)
        self.assertIn('"account takeover risks"', stt_rs)
        self.assertIn('("defsy cops", "DevSecOps")', stt_rs)
        self.assertIn('("trife roads", "traceroute")', stt_rs)
        self.assertIn('("BISC-64", "Base64")', stt_rs)
        self.assertIn('("Sertu", "cert")', stt_rs)
        self.assertIn('("dDevOps", "DevOps")', stt_rs)
        self.assertIn('("delops", "DevOps")', stt_rs)
        self.assertIn('("PDX", "TDX")', stt_rs)
        self.assertIn('("QD2", "K2")', stt_rs)
        self.assertIn('("ИК-2", "K2")', stt_rs)
        self.assertIn('("ка-2", "K2")', stt_rs)
        self.assertIn('("канал ИК-2", "канал K2")', stt_rs)
        self.assertIn('("hsam", "HSM")', stt_rs)
        self.assertIn('("PCC", "PC/SC")', stt_rs)
        self.assertIn('("dimetime", "downtime")', stt_rs)
        self.assertIn('("GETLab", "GitLab")', stt_rs)
        self.assertIn('("Harva", "Harbor")', stt_rs)
        self.assertIn('("Netsus", "Nexus")', stt_rs)
        self.assertIn('("Volta", "Vault")', stt_rs)
        self.assertIn('("Twe City", "TeamCity")', stt_rs)
        self.assertIn('("not group", "node group")', stt_rs)
        self.assertIn('("firecraker", "Firecracker")', stt_rs)
        self.assertIn('("kicklog", "Keycloak")', stt_rs)
        self.assertIn('("jiva", "Jira")', stt_rs)
        self.assertIn('("Google Server Secutive", "Google Cybersecurity")', stt_rs)
        self.assertIn('("Select tell", "Selectel")', stt_rs)
        self.assertIn('("Sliktelry", "Selectel")', stt_rs)
        self.assertIn('("keyclock", "Keycloak")', stt_rs)
        self.assertIn('("OEDC", "OIDC")', stt_rs)
        self.assertIn('("UBK", "YubiKey")', stt_rs)
        self.assertIn('("Clibreprood tools", "CryptoPro tools")', stt_rs)
        self.assertIn('("CryptuPro", "CryptoPro")', stt_rs)
        self.assertIn('("CryptoProp", "CryptoPro")', stt_rs)
        self.assertIn('("Copois", "CryptoPro CSP")', stt_rs)
        self.assertIn('("Treshare IP", "Treasure API")', stt_rs)
        self.assertIn('("Cafку", "Kafka")', stt_rs)
        self.assertIn('("SSSH", "SSH")', stt_rs)
        self.assertIn('("SOKET", "socket")', stt_rs)
        self.assertIn('("Registery", "registry")', stt_rs)
        self.assertIn('("boost", "Burp Suite")', stt_rs)
        self.assertIn('("Burg Suite Professional", "Burp Suite Professional")', stt_rs)
        self.assertIn('("о вас к западу", "OWASP ZAP")', stt_rs)
        self.assertIn('("Nucai", "Nuclei")', stt_rs)
        self.assertIn('("SimGreb", "Semgrep")', stt_rs)
        self.assertIn('("sing grap", "Semgrep")', stt_rs)
        self.assertIn('("eTrivy", "Trivy")', stt_rs)
        self.assertIn('("defect dother", "DefectDojo")', stt_rs)
        self.assertIn('("возух", "Wazuh")', stt_rs)
        self.assertIn('("сока налиток", "SOC analyst")', stt_rs)
        self.assertIn('("рандбук", "runbook")', stt_rs)
        self.assertIn('("eam politik", "IAM policies")', stt_rs)
        self.assertIn('("cluster admin", "cluster-admin")', stt_rs)
        self.assertIn('("forwall", "firewall")', stt_rs)
        self.assertIn('("wav", "WAF")', stt_rs)
        self.assertIn('("TownScript", "TypeScript")', stt_rs)
        self.assertIn('("SAG ключи", "SSH ключи")', stt_rs)
        self.assertIn("const MAX_KEYTERM_QUERY_CHARS: usize = 2_500", stt_rs)
        self.assertIn("fn deepgram_keyterms_supported(language: &str) -> bool", stt_rs)
        self.assertIn("fn normalize_appsec_terms(text: &str) -> String", stt_rs)
        self.assertIn("let completed_transcript = normalize_appsec_terms", stt_rs)


if __name__ == "__main__":
    unittest.main()
